package com.example.officesecurity.controller;


import com.example.officesecurity.csv.CSVUtils;
import com.example.officesecurity.model.CsvUserDAO;
import com.example.officesecurity.model.EventEntity;
import com.example.officesecurity.model.ResponseMessage;
import com.example.officesecurity.model.UserDAO;
import com.example.officesecurity.repository.TimeRepository;
import com.example.officesecurity.repository.UserRepository;
import com.example.officesecurity.service.UserService;
import com.example.officesecurity.service.impl.UserDTO;
import lombok.RequiredArgsConstructor;
import org.apache.commons.csv.CSVFormat;
import org.apache.commons.csv.CSVPrinter;
import org.springframework.core.io.InputStreamResource;
import org.springframework.core.io.Resource;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import javax.servlet.http.HttpServletResponse;
import java.io.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

@RestController // This means that this class is a RestController
@RequiredArgsConstructor// This means to get the bean called userRepository
@RequestMapping(path = "/demo") // This means URL's start with /demo (after Application path)
public class UserController {

    // Which is auto-generated by Spring, we will use it to handle the data
    private final UserService userService;
    private final UserRepository userRepository;
    private final TimeRepository timeRepository;

    @PostMapping(path = "/users/register")
    public ResponseEntity<ResponseMessage> registerUser(@RequestBody UserDTO newUser) {


        userService.addUser(newUser);
        return ResponseEntity.ok(ResponseMessage.builder().message("Good").build());
    }

    //!!!
    @PostMapping("/users/login")
    public ResponseEntity<ResponseMessage> loginUsers(@RequestBody UserDTO userDTO) {

        userService.loginUser(userDTO);

        return ResponseEntity.ok(ResponseMessage.builder().message("Good").build());
    }

    @PostMapping("/users/logout")
    public ResponseEntity<ResponseMessage> logUserOut(@RequestBody UserDTO userDTO) {

        userService.logoutUser(userDTO);

        return ResponseEntity.ok(ResponseMessage.builder().message("Good").build());
    }


    @GetMapping(path = "/all")
    public List<UserDAO> getAllUsers(@RequestParam Integer pageNo, Integer pageSize, String sortBy) {
        return userService.getAllUsersByPages(pageNo, pageSize, sortBy);

    }

    @GetMapping(path = "/time")
    public List<EventEntity> getTimeLogs() {
        return userService.getTimeLogs();
    }

    @GetMapping(path = "/getTimeLogs")
    public List<EventEntity> getLogsForSpecificTime(String start, String end) {

        return userService.getLogsForSpecificTime(start, end);

    }

    @GetMapping(path = "/all/remove")
    public ResponseEntity<ResponseMessage> removeAllUsers() {
        // This returns a JSON or XML with the users
        userRepository.deleteAll();
        timeRepository.deleteAll();
        return ResponseEntity.ok(ResponseMessage.builder().message("Data was deleted successfully!").build());
    }

    @GetMapping(path = "getCSVFile/userDAO.csv")
    public void downloadCsv(HttpServletResponse response) throws IOException {
        response.setContentType("text/csv");
        response.setHeader("Content-Disposition", "attachment; file=usersDAO.csv");
        CSVUtils.downloadCsv(response.getWriter(), createTestData());
    }

    private List<UserDAO> createTestData() {
        List<UserDAO> userDAOList = userService.findAll();
        return userDAOList;
    }

}



